name: ES Schema generation

on: workflow_dispatch

jobs:
    dev-deployment:
        if: contains( github.ref, 'development')
        runs-on: ubuntu-latest
        container: node:16-alpine
        environment: dev
        steps:
          - name: Setting up environment for build...
            run: |
              apk add --no-cache git maven bash curl wget
              apk --no-cache add openjdk17-jdk
              apk add --no-cache python3 py3-pip
              curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-425.0.0-linux-x86_64.tar.gz > /tmp/google-cloud-cli.tar.gz
              mkdir -p /usr/local/gcloud
              tar -xzf /tmp/google-cloud-cli.tar.gz -C /usr/local/gcloud
              chmod -R 777 /usr/local/gcloud/
              /usr/local/gcloud/google-cloud-sdk/install.sh --quiet
              PATH=$PATH:/usr/local/gcloud/google-cloud-sdk/bin
